### ISSUE TITLE
Kite for JupyterLab not working

### ISSUE THREAD

**Issue by royschwartz2** [kiteco/issue-tracker#526] opened 2020-12-28 14:05 UTC
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x ] Include your Kite application logs, _taken while you are experiencing your issue_.

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/119308/kite_local/client.log.2020-12-28_01-56-32-PM.bak.gz

- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
I installed Kite for JupyterLab following the instructions here. https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin. Unfortunately, there is no sign of Kite (no icon at the bottom left (see screenshot) and no completions). 

Additional information:
- OS: MacOS 11.1
- The output of jupyter labextension list 

JupyterLab v3.0.0
Other labextensions (built into JupyterLab)
   app dir: /Users/royschwartz/Library/Python/3.7/share/jupyter/lab
        @jupyterlab/git v0.23.3 enabled  X
        @kiteco/jupyterlab-kite v1.2.0 enabled OK
        jupyterlab-system-monitor v0.7.0 enabled OK
        jupyterlab-theme-toggle v0.6.1 enabled OK
        jupyterlab-topbar v0.6.0 enabled OK
        jupyterlab-topbar-extension v0.6.0 enabled OK
        jupyterlab-topbar-text v0.6.1 enabled OK
        nbdime-jupyterlab v2.0.1 enabled  X

   The following extension are outdated:
        @jupyterlab/git
        nbdime-jupyterlab

   Consider running "jupyter labextension update --all" to check for updates.

- and jupyter serverextension list:

config dir: /Users/royschwartz/.jupyter
    jupyter_nbextensions_configurator  enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK

- The output of pip list:

Package                           Version    Location
--------------------------------- ---------- --------------------------------
aiohttp                           3.6.2
anyio                             2.0.2
appdirs                           1.4.3
appnope                           0.1.0
async-timeout                     3.0.1
attr                              0.3.1
attrs                             19.1.0
Babel                             2.9.0
backcall                          0.1.0
bcrypt                            3.1.7
beautifulsoup4                    4.9.1
BiobankRead2                      3.1
bleach                            3.1.0
blis                              0.4.1
boto3                             1.12.32
botocore                          1.15.49
bs4                               0.0.1
cachetools                        4.1.1
certifi                           2019.11.28
cffi                              1.14.0
chardet                           3.0.4
Click                             7.0
colorama                          0.4.4
construct                         2.10.56
cryptography                      2.8
cycler                            0.10.0
cymem                             2.0.3
decorator                         4.4.0
defusedxml                        0.6.0
descartes                         1.1.0
dictdiffer                        0.8.1
docopt                            0.6.2
docutils                          0.15.2
dtlpy                             1.17.12
entrypoints                       0.3
flake8                            3.7.7
Flask                             1.1.1
Flask-API                         2.0
Flask-WTF                         0.14.3
fuzzyfinder                       2.1.0
gitdb                             4.0.5
GitPython                         3.1.11
Glymur                            0.9.2
google-api-core                   1.21.0
google-auth                       1.19.2
google-cloud-core                 1.3.0
google-cloud-storage              1.28.1
google-resumable-media            0.5.1
googleapis-common-protos          1.52.0
htmlmin                           0.1.12
idna                              2.8
imageio                           2.8.0
imageio-ffmpeg                    0.4.2
imgviz                            1.2.1
importlib-metadata                0.23
ipykernel                         5.1.3
ipython                           7.8.0
ipython-genutils                  0.2.0
itsdangerous                      1.1.0
jedi                              0.15.1
Jinja2                            2.10.3
jmespath                          0.10.0
joblib                            0.15.1
json5                             0.9.5
jsonschema                        3.2.0
jupyter-client                    6.1.7
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.6.1
jupyter-highlight-selected-word   0.2.0
jupyter-kite                      1.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-server                    1.1.3
jupyterlab                        3.0.0
jupyterlab-git                    0.23.3
jupyterlab-server                 2.0.0
jupyterlab-topbar                 0.6.0
kiwisolver                        1.2.0
label-studio                      0.7.3
label-studio-converter            0.0.17
labelme                           4.5.6
littleutils                       0.2.2
lxml                              4.4.1
MarkupSafe                        1.1.1
matplotlib                        3.2.1
mccabe                            0.6.1
mistune                           0.8.4
mixpanel                          4.4.0
mizani                            0.7.2
more-itertools                    7.2.0
mpldatacursor                     0.7.1
multidict                         4.7.6
mysqlclient                       1.4.6
natsort                           7.0.1
nbclassic                         0.2.5
nbconvert                         5.6.0
nbdime                            2.1.0
nbformat                          4.4.0
nbresuse                          0.4.0
notebook                          6.0.1
numpy                             1.17.4
oct-converter                     0.1        /Users/royschwartz/OCT-Converter
opencv-python                     4.2.0.34
optional-django                   0.1.0
orjson                            3.2.2
outdated                          0.2.0
packaging                         20.8
palettable                        3.3.0
pandas                            1.1.4
pandas-flavor                     0.2.0
pandocfilters                     1.4.2
paramiko                          2.7.1
parso                             0.5.1
pathspec                          0.8.0
patsy                             0.5.1
pexpect                           4.7.0
pickleshare                       0.7.5
Pillow                            7.2.0
pingouin                          0.3.8
pip                               20.2.4
plotnine                          0.7.1
prometheus-client                 0.7.1
prompt-toolkit                    2.0.10
protobuf                          3.12.2
psutil                            5.8.0
ptyprocess                        0.6.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.5.0
pycparser                         2.19
pydicom                           2.0.0
pyflakes                          2.1.1
Pygments                          2.4.2
PyJWT                             1.7.1
PyNaCl                            1.3.0
pyparsing                         2.4.7
pypyodbc                          1.3.4
PyQt5                             5.15.0
PyQt5-sip                         12.8.0
pyrsistent                        0.15.4
python-dateutil                   2.8.1
pytz                              2019.3
PyYAML                            5.1.2
pyzmq                             18.1.0
QtPy                              1.9.0
rarfile                           3.2
rdata                             0.2.1
redis                             3.5.3
regex                             2020.6.8
requests                          2.22.0
requests-toolbelt                 0.9.1
rq                                1.4.3
rsa                               4.6
s3transfer                        0.3.3
scikit-datasets                   0.1.38
scikit-fda                        0.3
scikit-learn                      0.23.1
scikit-misc                       0.1.3
scipy                             1.4.1
scitools3                         1.0
seaborn                           0.10.1
Send2Trash                        1.5.0
setuptools                        41.2.0
similaritymeasures                0.4.3
six                               1.12.0
smmap                             3.0.4
sniffio                           1.2.0
soupsieve                         2.0.1
srsly                             0.2.0
sshtunnel                         0.1.5
statsmodels                       0.12.0
tableone                          0.7.9
tabulate                          0.8.7
termcolor                         1.1.0
terminado                         0.9.1
testpath                          0.4.2
threadpoolctl                     2.0.0
tornado                           6.1
tqdm                              4.40.2
traitlets                         4.3.3
typing-extensions                 3.7.4.2
urllib3                           1.25.7
validators                        0.17.1
wasabi                            0.4.2
wcwidth                           0.1.7
webencodings                      0.5.1
webvtt-py                         0.4.3
Werkzeug                          0.16.0
WTForms                           2.3.1
xarray                            0.15.1
xlrd                              1.2.0
xmljson                           0.2.0
yarl                              1.5.1
zipp                              0.6.0

**Screenshots**
![CleanShot 2020-12-28 at 13 55 56](https://user-images.githubusercontent.com/51368065/103219195-ef6cf180-4914-11eb-954c-f71f77162dfe.png)

**Comment by edzkite** [comment] 2021-01-04 20:24
Please see https://github.com/kiteco/issue-tracker/issues/532#issuecomment-754197763. Closing as duplicate of #532

**Closed by edzkite** 2021-01-04 20:24 UTC
Labels: jupyterlab plugin

**Comment by edzkite** [comment] 2021-01-08 23:43
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!
