### ISSUE TITLE
Jupyterlab plugin not connecting to desktop app

### ISSUE THREAD

**Issue by jimenezj8** [kiteco/issue-tracker#419] opened 2020-10-07 17:32 UTC
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

The only error I experience in installing the Kite plugin for Jupyterlab is in launching Jupyterlab; I've correctly installed the jupyter-kite extension with pip, and added it to my jupyter labextension list. No upgrades are available after checking jupyterlab and the Kite extension. The error states that the Kite extension will not work because the Kite desktop application is not installed; however, I know it is because the application works in Atom.

Also, the only extension I have installed for Jupyterlab is the Kite plugin.

**Screenshots**

**Comment by its-dhung** [comment] 2020-11-10 01:15
Sounds like a duplicate of #409.

**Closed** 2020-11-10 01:15 UTC
Labels: duplicate
