### ISSUE TITLE
Kite plugin is not compatible with intellij IDEA 2021.1

### ISSUE THREAD

**Issue by arnonmoscona** [kiteco/issue-tracker#720] opened 2021-04-08 16:46 UTC
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
After updating IntellijIDEA to 2021.1 the IDE reports that the Kite plugin is incompatible and must be disabled.
No logs available, as plugin is disabled by the IDE.

**Screenshots**

**Comment by tonycheang** [comment] 2021-04-08 17:03
Thanks for the report. I believe this is a dupe of https://github.com/kiteco/issue-tracker/issues/716, but the additional information that this happened on update was very helpful!

**Closed as completed by tonycheang** 2021-04-08 17:03 UTC
Labels: bug
