### ISSUE TITLE
kite unables to detect intellij IDE when installed using flatpak

### ISSUE THREAD

**Issue by byteshiva** [kiteco/issue-tracker#466] opened 2020-11-07 00:23 UTC
Unable to detect intellij when installed using flatpak

**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [x] Include your Kite application logs, _taken while you are experiencing your issue_.
- [x] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/551616/kite_local/client.log.2020-11-07_05-50-47-AM.bak.gz

**Screenshots**

![image](https://user-images.githubusercontent.com/10637299/98426068-7d6aef80-20bd-11eb-8bd1-d9abec3bbfce.png)

**Comment by byteshiva** [comment] 2020-11-07 00:26
https://s3.console.aws.amazon.com/s3/object/kite-client-capture/prod/551616/kite_local/1604708636759493073/capture.gz

**Comment by its-dhung** [comment] 2020-11-10 02:22
Duplicate of #260

**Closed by its-dhung** 2020-11-10 02:22 UTC
