### ISSUE TITLE
When I run "KiteSetupSplashScreen" it just load for a minute and then a error pops up

### ISSUE THREAD

**Issue by Far00K** [kiteco/issue-tracker#264] opened 2020-06-15 20:27 UTC
After downloading kite from "https://kite.com/download/". I started th setup program u download. 

Then I got this after I restarted VS Code:
![kiteproblöem 2](https://user-images.githubusercontent.com/27159994/84701659-af848500-af55-11ea-89c2-81c59ad97276.PNG)

So I started "KiteSetupSplashScreen" bcs I think what they mean to complete the kite installation. But then I start it and it just load. And what I get is a new window
![kiteProblem](https://user-images.githubusercontent.com/27159994/84702627-3c7c0e00-af57-11ea-83b8-a6ac363a673a.PNG)

**Comment by its-dhung** [comment] 2020-07-06 17:13
Duplicate of #158

**Closed by its-dhung** 2020-07-06 17:13 UTC

**Comment by sahsz123** [comment] 2020-07-11 06:10
The same issue, the log. ../AppData\Local\Kite\logs has only copilot.log with 2 lines there:


2020-07-11T06:06:16.805Z [copilot] error: unhandled error spawn UNKNOWN
2020-07-11T06:06:26.731Z [copilot] error: unhandled error spawn UNKNOWN
