### ISSUE TITLE
kite: not running

### ISSUE THREAD

**Issue by ahmadmustafaanis** [kiteco/issue-tracker#369] opened 2020-08-30 11:13 UTC
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.

- [x] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [x] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.

* OS UBUNTU 18.04
* NODE VErsions = 10.22.0
* Python 3.7
Installed the node, kite, kite for jupyter but When I see bottom, I see `kite: not running`, and there is no autocomplete etc.

**Screenshots**
![Screenshot from 2020-08-30 16-12-37](https://user-images.githubusercontent.com/47111429/91657608-c27e0e80-eadb-11ea-9824-0ec901cd5078.png)

**Comment by forfuns** [comment] 2020-09-05 20:46
same issue

**Comment by kylemichaelreaves** [comment] 2020-09-13 23:51
Same.

**Comment by edzkite** [comment] 2020-09-22 18:30
Closing as duplicate of https://github.com/kiteco/issue-tracker/issues/380

**Closed by edzkite** 2020-09-22 18:30 UTC
