### ISSUE TITLE
"Set your Copilot to always be your top window" on MacOS is gone

### ISSUE THREAD

**Issue by dsaad68** [kiteco/issue-tracker#213] opened 2020-05-12 14:59 UTC
I updated to Kite (version: 0.20200510.0) on macOS (Version:10.15.4) and after that I lost "Set your Copilot to always be your top window" in the Settings menu.

**Comment by its-dhung** [comment] 2020-05-13 18:30
Duplicate of #201. We'll be fixing this in the upcoming weeks.

**Closed by its-dhung** 2020-05-13 18:30 UTC
