### ISSUE TITLE
Enormous amount of logs written in syslog.1 file in ubuntu

### ISSUE THREAD

**Issue by StefanoPierini** [kiteco/issue-tracker#251] opened 2020-06-04 09:50 UTC
**application log**
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/208232/kite_local/client.log.2020-06-04_11-40-51-AM.bak.gz

**Describe the bug**
My syslog.1 file in "/var/log" directory under ubuntu is getting bigger and bigger. looking to the lines I noticed that the most of them appears like the followings:
```
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70926336/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70942720/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70959104/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70967296/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70975488/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 70991872/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 71008256/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 71024640/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 71041024/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 71057408/443842547
Jun  4 11:01:13 p-pierinis kite-update[9329]: Download: 71073792/443842547
```
At the moment, the file is 16.6Gb.

**Comment by luisabellan** [comment] 2020-06-08 16:29
The updater activates and freezes my system.
https://gyazo.com/e2efadb641a6155fdad38ca09f91ffb2

**Comment by jansorg** [comment] 2020-06-12 15:29
@StefanoPierini Thanks for reporting this. Kite's updater is supposed to not show progress information for updates. But it's still printing progress information if no existing installation was found.
Could you run `~/.local/share/kite/update` in a terminal and post the output, please?

If you want, you can turn off the updates by running this as the user who installed kite:
```
systemctl disable --user kite-updater.timer
```

A fix for this will most likely be released next week. It'll configure the systemd service to never print the output of the update command into the log file.

**Comment by jansorg** [comment] 2020-06-12 15:34
@luisabellan Thanks for the report! I think that this is a separate issue.
If you don't like the update check in the background, you can disable it by running this:
```
systemctl disable --user kite-updater.timer
```
You can still update manually by running `~/.local/share/kite/update`.

I don't think that the first messages about a process running as root are caused by kite. It's not running as root and the update service is a systemd user service.
The messages on `posix_spawn` don't seem to be related to kite. You could disable the updater and check if the messages are still showing up in your log.

**Comment by StefanoPierini** [comment] 2020-06-12 16:17
@jansorg yes, here is the output
```
[updater] found version 2.20200609.2 installed
[updater] already up to date!
```

**Comment by jansorg** [comment] 2020-06-19 10:28
@StefanoPierini Hm, that's a bit weird. The latest releases of kited include a change, which never writes output of the updater service into your journal. 
In case that this is helpful: you can shrink the huge journal with one of the `--vacuum-size=, --vacuum-time=, --vacuum-files=` options of journalctl. See `man journalctl` for details.
`

**Closed by jansorg** 2020-06-19 10:28 UTC
Labels: bug, prioritized
