### ISSUE TITLE
Not working with Jupyter Lab 3.x

### ISSUE THREAD

**Issue by orome** [kiteco/issue-tracker#521] opened 2020-12-25 15:12 UTC
**Describe the bug**
Following an update from to Jupyter Lab 3.x, the kite extension loads but does not run: no indication of status and completions do not work.

**Comment by teremterem** [comment] 2020-12-26 13:13
In Jupyter Lab 3.x completions did not work for me both **with and without** Kite extension. I was receiving this exception:
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
```
Turned out **jedi** rolled out an incompatible version yesterday (**0.18.0**). I downgraded jedi to previous version (**0.17.2**) and completions now work. However, those completions aren't Kite completions. Kite extension seems to still have no effect.

**Comment by RodolfoFigueroa** [comment] 2020-12-29 22:04
> In Jupyter Lab 3.x completions did not work for me both **with and without** Kite extension. I was receiving this exception:
> 
> ```
> [IPKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
>     yield gen.maybe_future(handler(stream, idents, msg))
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
>     value = future.result()
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
>     yielded = ctx_run(next, result)
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
>     matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
>     return self._experimental_do_complete(code, cursor_pos)
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
>     completions = list(_rectify_completions(code, raw_completions))
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions
>     completions = list(completions)
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions
>     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions
>     matched_text, matches, matches_origin, jedi_matches = self._complete(
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete
>     completions = self._jedi_matches(
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
>     interpreter = jedi.Interpreter(
>   File "/Users/terem/.local/share/virtualenvs/swipe-thought-bot-dKSXIKA3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__
>     super().__init__(code, environment=environment,
> TypeError: __init__() got an unexpected keyword argument 'column'
> ```
> 
> Turned out **jedi** rolled out an incompatible version yesterday (**0.18.0**). I downgraded jedi to previous version (**0.17.2**) and completions now work.
> 
> However, those completions aren't Kite completions. Kite extension seems to still have no effect.

Thanks, I was wondering why completions weren't working.

**Comment by edzkite** [comment] 2021-01-04 20:26
@teremterem Thanks for the find! 

In addition, it looks like JupyterLab 3.0 is causing our extension to break. Please see https://github.com/kiteco/issue-tracker/issues/532#issuecomment-754197763 for more details. Closing as duplicate of #532.

**Closed by edzkite** 2021-01-04 20:26 UTC
Labels: jupyterlab plugin

**Comment by edzkite** [comment] 2021-01-08 23:43
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!
