### ISSUE TITLE
Kite extension does not show up in JupyterLab

### ISSUE THREAD

**Issue by maxistaebler** [kiteco/issue-tracker#525] opened 2020-12-28 13:22 UTC
I'm using MacOS BigSur (11.1) and installed the kite extension for JupyterLab according to the [docs](https://help.kite.com/article/143-how-to-install-the-jupyterlab-plugin). Anyways, when I open jupyterlab I do not see the kite symbol at the bottom off my screen and there is no autocompletion suggestion. Kite app is running on my Mac.

Here the specs:

**Console logs:**

```bash
[I 2020-12-28 14:16:43.341 ServerApp] jupyterlab | extension was successfully linked.
[I 2020-12-28 14:16:43.573 ServerApp] jupyter_kite | extension was found and enabled by nbclassic. Consider moving the extension to Jupyter Server's extension paths.
[I 2020-12-28 14:16:43.573 ServerApp] jupyter_kite | extension was successfully linked.
[I 2020-12-28 14:16:43.573 ServerApp] nbclassic | extension was successfully linked.
[I 2020-12-28 14:16:43.733 ServerApp] jupyter_kite | extension was successfully loaded.
[I 2020-12-28 14:16:43.734 LabApp] JupyterLab extension loaded from /Users/maximilianstaebler/opt/miniconda3/envs/ds/lib/python3.9/site-packages/jupyterlab
[I 2020-12-28 14:16:43.734 LabApp] JupyterLab application directory is /Users/maximilianstaebler/opt/miniconda3/envs/ds/share/jupyter/lab
[I 2020-12-28 14:16:43.737 ServerApp] jupyterlab | extension was successfully loaded.
[I 2020-12-28 14:16:43.742 ServerApp] nbclassic | extension was successfully loaded.
[I 2020-12-28 14:16:43.746 ServerApp] Serving notebooks from local directory: /Users/maximilianstaebler/Library/Mobile Documents/com~apple~CloudDocs/code/udemy/linear-algebra
[I 2020-12-28 14:16:43.746 ServerApp] Jupyter Server 1.1.3 is running at:
[I 2020-12-28 14:16:43.746 ServerApp] http://localhost:8888/lab?token=5af51a9f01fba543fcaee8b811c9b42f37177d61a32e8bbc
[I 2020-12-28 14:16:43.746 ServerApp]  or http://127.0.0.1:8888/lab?token=5af51a9f01fba543fcaee8b811c9b42f37177d61a32e8bbc
[I 2020-12-28 14:16:43.746 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2020-12-28 14:16:43.750 ServerApp]

    To access the server, open this file in a browser:
        file:///Users/maximilianstaebler/Library/Jupyter/runtime/jpserver-37625-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=5af51a9f01fba543fcaee8b811c9b42f37177d61a32e8bbc
     or http://127.0.0.1:8888/lab?token=5af51a9f01fba543fcaee8b811c9b42f37177d61a32e8bbc
[I 2020-12-28 14:16:48.377 LabApp] Build is up to date
|[I 2020-12-28 14:16:50.036 ServerApp] Kernel started: bface34d-aef4-4020-bf58-b6c382a8cbc7
```

**JupyterLab extension list:**

```bash
JupyterLab v3.0.0
Other labextensions (built into JupyterLab)
   app dir: /Users/maximilianstaebler/opt/miniconda3/envs/ds/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.2.0 enabled OK


Uninstalled core extensions:
    @kiteco/jupyterlab-kite
```

**JuypterLab serverextension list:**

```bash
config dir: /Users/maximilianstaebler/opt/miniconda3/envs/ds/etc/jupyter
    jupyter_kite  enabled
    - Validating...
      jupyter_kite 1.2.0 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.0 OK
```

**Conda env:**

```bash
# packages in environment at /Users/maximilianstaebler/opt/miniconda3/envs/ds:
#
# Name                    Version                   Build  Channel
anyio                     2.0.2            py39h6e9494a_2    conda-forge
appnope                   0.1.2            py39h6e9494a_0    conda-forge
argon2-cffi               20.1.0           py39h5a22ff9_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py39h66d5b7b_1001    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_0    conda-forge
cffi                      1.14.4           py39h7786acb_1    conda-forge
chardet                   4.0.0            py39h6e9494a_0    conda-forge
cryptography              3.3.1            py39h79a2c39_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h3f75d11_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.3.0            py39h6e9494a_2    conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    conda-forge
ipykernel                 5.4.2            py39h71a6800_0    conda-forge
ipython                   7.19.0           py39h71a6800_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jedi                      0.18.0           py39h6e9494a_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter-kite              1.2.0                    pypi_0    pypi
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.7.0            py39h6e9494a_0    conda-forge
jupyter_server            1.1.3            py39h6e9494a_0    conda-forge
jupyterlab                3.0.0              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.0.0              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py39heea7e63_0    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0               h6c81a4c_15    conda-forge
libgfortran5              9.3.0               h6c81a4c_15    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1            py39h66d5b7b_2    conda-forge
matplotlib-base           3.3.3            py39h5674cf4_0    conda-forge
mistune                   0.8.4           py39h5a22ff9_1002    conda-forge
nbclassic                 0.2.5              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py39h6e9494a_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
notebook                  6.1.6            py39h6e9494a_0    conda-forge
numpy                     1.19.4           py39he588a01_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.2.0            py39h089d6f7_0    conda-forge
pandoc                    2.11.3.1             h35c211d_0    conda-forge
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.1                    pypi_0    pypi
patsy                     0.5.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py39h38d7768_0    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
plotly                    4.14.1             pyhd3deb0d_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py39h5a22ff9_1    conda-forge
pysocks                   1.7.1            py39h2c36a5b_2    conda-forge
python                    3.9.1           h1d169a7_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyzmq                     20.0.0                   pypi_0    pypi
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-learn              0.24.0           py39h1f17f7f_0    conda-forge
scipy                     1.5.3            py39h3164f57_0    conda-forge
seaborn                   0.11.1               h694c41f_0    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py39h2c36a5b_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sniffio                   1.2.0            py39h6e9494a_0    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
statsmodels               0.12.1           py39hf24ec92_1    conda-forge
terminado                 0.9.1            py39h6e9494a_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tornado                   6.1              py39h5a22ff9_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzdata                    2020e                he74cb21_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py39h6e9494a_4    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.3                h74dc148_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge
```

**Comment by edzkite** [comment] 2021-01-04 20:24
Please see https://github.com/kiteco/issue-tracker/issues/532#issuecomment-754197763. Closing as duplicate of #532.

**Closed by edzkite** 2021-01-04 20:24 UTC
Labels: jupyterlab plugin

**Comment by edzkite** [comment] 2021-01-08 23:43
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!
