### ISSUE TITLE
Kite: Not Running on Jupyter Lab

### ISSUE THREAD

**Issue by karanrshah96** [kiteco/issue-tracker#401] opened 2020-09-21 11:56 UTC
**Required Information**
To help us triage your issue effectively, please make sure you've completed these steps before opening this issue. Issues with not enough information may be deprioritized or ignored.
- [ ] [Read our guide](https://help.kite.com/article/96-contact-us-with-logs) on how to report an issue.
- [ ] Include your Kite application logs, _taken while you are experiencing your issue_.
- [ ] If reporting a performance problem, include your resource usage logs, _taken while you are experiencing your issue_.
- [ ] If reporting an issue with Kite's editor plugin, include which editor you are using and the version, and any accompanying logs from your editor's console.

**Describe the bug**
A clear description of what the bug is. Include steps to reproduce the bug if necessary.
OS: Ubuntu 20.04
Kite App: Installed, works on Atom IDE
Error: Even after setup, Kite:Not Running message in Jupyter Lab
Pip List:
Package                Version             
---------------------- --------------------
apturl                 0.5.2               
argon2-cffi            20.1.0              
async-generator        1.10                
attrs                  20.2.0              
backcall               0.2.0               
bcrypt                 3.1.7               
bleach                 3.2.1               
blinker                1.4                 
Brlapi                 0.7.0               
certifi                2020.6.20           
cffi                   1.14.3              
chardet                3.0.4               
chrome-gnome-shell     0.0.0               
Click                  7.0                 
colorama               0.4.3               
command-not-found      0.3                 
cryptography           2.8                 
cupshelpers            1.0                 
cycler                 0.10.0              
dbus-python            1.2.16              
decorator              4.4.2               
defer                  1.0.6               
defusedxml             0.6.0               
distro                 1.4.0               
distro-info            0.23ubuntu1         
duplicity              0.8.12.0            
entrypoints            0.3                 
fasteners              0.14.1              
future                 0.18.2              
httplib2               0.14.0              
idna                   2.8                 
ipykernel              5.3.4               
ipython                7.18.1              
ipython-genutils       0.2.0               
ipywidgets             7.5.1               
jedi                   0.17.2              
Jinja2                 2.11.2              
joblib                 0.16.0              
json5                  0.9.5               
jsonschema             3.2.0               
jupyter                1.0.0               
jupyter-client         6.1.7               
jupyter-console        6.2.0               
jupyter-core           4.6.3               
jupyter-kite           1.0.0               
jupyterlab             2.2.8               
jupyterlab-pygments    0.1.1               
jupyterlab-server      1.2.0               
keyring                18.0.1              
kiwisolver             1.2.0               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
libevdev               0.5                 
lockfile               0.12.2              
louis                  3.12.0              
macaroonbakery         1.3.1               
Mako                   1.1.0               
MarkupSafe             1.1.0               
matplotlib             3.3.2               
mistune                0.8.4               
monotonic              1.5                 
nbclient               0.5.0               
nbconvert              6.0.4               
nbformat               5.0.7               
nest-asyncio           1.4.0               
netifaces              0.10.4              
notebook               6.1.4               
numpy                  1.19.2              
oauthlib               3.1.0               
olefile                0.46                
packaging              20.4                
pandas                 1.1.2               
pandocfilters          1.4.2               
paramiko               2.6.0               
parso                  0.7.1               
pexpect                4.6.0               
pickleshare            0.7.5               
Pillow                 7.0.0               
pip                    20.0.2              
prometheus-client      0.8.0               
prompt-toolkit         3.0.7               
protobuf               3.6.1               
ptyprocess             0.6.0               
pycairo                1.16.2              
pycparser              2.20                
pycups                 1.9.73              
Pygments               2.7.1               
PyGObject              3.36.0              
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyparsing              2.4.7               
pyRFC3339              1.1                 
pyrsistent             0.17.3              
python-apt             2.0.0+ubuntu0.20.4.1
python-dateutil        2.7.3               
python-debian          0.1.36ubuntu1       
pytz                   2019.3              
pyudev                 0.21.0              
pyxdg                  0.26                
PyYAML                 5.3.1               
pyzmq                  19.0.2              
qtconsole              4.7.7               
QtPy                   1.9.0               
reportlab              3.5.34              
requests               2.22.0              
requests-unixsocket    0.2.0               
scikit-learn           0.23.2              
scipy                  1.5.2               
SecretStorage          2.3.1               
Send2Trash             1.5.0               
setuptools             45.2.0              
simplejson             3.16.0              
six                    1.14.0              
systemd-python         234                 
terminado              0.9.1               
testpath               0.4.4               
threadpoolctl          2.1.0               
tornado                6.0.4               
traitlets              5.0.4               
ubuntu-advantage-tools 20.3                
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.25.8              
usb-creator            0.3.7               
wadllib                1.3.3               
wcwidth                0.2.5               
webencodings           0.5.1               
wheel                  0.34.2              
widgetsnbextension     3.5.1               
xkit                   0.0.0 

jupyter labextension list:
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/karan/.local/share/jupyter/lab
        @kiteco/jupyterlab-kite v1.0.0  enabled  OK

**Screenshots**

**Comment by edzkite** [comment] 2020-09-22 01:30
What's the output of `jupyter serverextension list`?

**Comment by edzkite** [comment] 2020-09-22 01:30
Closing as duplicate of https://github.com/kiteco/issue-tracker/issues/380

**Closed by edzkite** 2020-09-22 01:30 UTC
