### ISSUE TITLE
"Kite: not running" on jupyterlab 

### ISSUE THREAD

**Issue by KermaniMojtaba** [kiteco/issue-tracker#344] opened 2020-08-13 07:07 UTC
I'm trying to get the kite working with Jupyter lab. I followed the installation, installed the Kite desktop app and jupyterlab extensions, and I'm using jupyterlab version 2.3. However, the jupyterlab says "Kite: not running". 
here are packages and extensions: 
Package                Version
---------------------- ---------
asn1crypto             1.2.0
attrs                  19.3.0
backcall               0.1.0
bar-chart-race         0.0.6
bleach                 3.1.4
certifi                2020.6.20
cffi                   1.13.0
chardet                3.0.4
colorama               0.4.3
conda                  4.8.3
conda-package-handling 1.6.0
cryptography           2.8
cycler                 0.10.0
Cython                 0.29.17
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
glob2                  0.7
idna                   2.8
imageio                2.8.0
imageio-ffmpeg         0.4.1
importlib-metadata     1.6.0
ipykernel              5.2.1
ipython                7.13.0
ipython-genutils       0.2.0
ipython-sql            0.3.9
ipywidgets             7.5.1
jedi                   0.17.0
Jinja2                 2.11.2
joblib                 0.15.1
json5                  0.9.5
jsonschema             3.2.0
jupyter-client         6.1.3
jupyter-core           4.6.3
jupyter-kite           1.0.0
jupyterlab             2.2.4
jupyterlab-server      1.2.0
kiwisolver             1.2.0
MarkupSafe             1.1.1
matplotlib             3.2.1
menuinst               1.4.16
mistune                0.8.4
mkl-fft                1.0.15
mkl-random             1.1.0
mkl-service            2.3.0
moviepy                1.0.3
nbconvert              5.6.1
nbformat               5.0.6
notebook               6.0.3
numpy                  1.18.1
pandas                 1.0.3
pandocfilters          1.4.2
parso                  0.7.0
patsy                  0.5.1
pickleshare            0.7.5
Pillow                 7.1.2
pip                    19.3.1
pmdarima               1.6.1
prettytable            0.7.2
proglog                0.1.9
prometheus-client      0.7.1
prompt-toolkit         3.0.5
pycosat                0.6.3
pycparser              2.19
pycurl                 7.43.0.5
Pygments               2.6.1
pyOpenSSL              19.0.0
pyparsing              2.4.7
PyQt5                  5.12.3
PyQt5-sip              4.19.18
PyQtWebEngine          5.12.1
pyrsistent             0.16.0
PySocks                1.7.1
python-dateutil        2.8.1
pytz                   2020.1
pywin32                223
pywinpty               0.5.7
pyzmq                  19.0.0
requests               2.22.0
ruamel-yaml            0.15.46
scikit-learn           0.23.1
scipy                  1.4.1
seaborn                0.10.1
Send2Trash             1.5.0
setuptools             41.4.0
six                    1.12.0
SQLAlchemy             1.3.15
sqlparse               0.3.1
statsmodels            0.11.1
terminado              0.8.3
testpath               0.4.4
threadpoolctl          2.1.0
tornado                6.0.4
tqdm                   4.36.1
traitlets              4.3.3
urllib3                1.24.2
wcwidth                0.1.9
webencodings           0.5.1
wheel                  0.33.6
widgetsnbextension     3.5.1
win-inet-pton          1.1.0
wincertstore           0.2
zipp                   3.1.0

 @jupyterlab/geojson-extension v2.0.1 enabled  ok
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok

can you help, please?

thanks

**Comment by its-dhung** [comment] 2020-08-17 16:49
Do you have multiple kernels installed or are you using a Docker/remote instance of JupyterLab?

**Comment by KermaniMojtaba** [comment] 2020-08-18 02:16
I have an installed jupyter kernel 
C:\Users\xxxx\Anaconda3\share\jupyter\kernels\python3

**Comment by its-dhung** [comment] 2020-08-20 23:20
Can you try the following:

1. Restart Kite.
2. Restart JupyterLab.
3. Try typing around in JupyterLab for a bit to see if Kite's status changes.
4. If it still says "not running", please [generate your logs](https://help.kite.com/article/96-contact-us-with-logs) from Kite's Copilot and share them in this issue.
5. Also, please share the contents of your browser's JavaScript console (in the tab where JupyterLab is running).

**Comment by djachoc** [comment] 2020-08-31 19:23
I have access to multiple Windows machine and I had this issue in a couple of them. I pinned it down to the `node.js`  requirement to install JupyterLab Extensions. I got this problem when I used the `conda install nodejs`. Instead when I installed the stable version of [Node.js](https://nodejs.org/en/) on top of Anaconda, it worked. No guarantee this will work for everyone, but it did for me to solve this issue.

**Comment by KermaniMojtaba** [comment] 2020-09-04 02:14
I've installed an updated version of Jupyterlab and now, the Kite:ready icon is disappeared. 
I tried to install "kiteco/jupyterlab-kite" from extension part of jupyterlab but I got an error (see attached screenshot ) telling me I need to install server extension through "pip install jupyter-kite". I have already installed jupyter-kite extension and when I tried to installed it again, I get bellow notification telling me that I have already installed it.  
Requirement already satisfied: jupyter-kite in c:\users\kermanim\anaconda3\lib\site-packages (1.0.0)

Here is the generated log: 
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/431145/kite_local/client.log.2020-09-04_10-47-32-AM.bak.gz

I have attached javascript console (see attached). It says I dont have jupyter/server proxy, which I have, see attached


<img width="295" alt="browser's JavaScript console" src="https://user-images.githubusercontent.com/20250871/92191824-1015c500-eea8-11ea-9791-d6988a239b37.PNG">
<img width="111" alt="extension" src="https://user-images.githubusercontent.com/20250871/92191830-1146f200-eea8-11ea-9f5e-d9be5cee2e14.PNG">
<img width="501" alt="server extension error" src="https://user-images.githubusercontent.com/20250871/92191832-11df8880-eea8-11ea-9583-403ac9b973b6.PNG">
<img width="501" alt="server extension error" src="https://user-images.githubusercontent.com/20250871/92191888-2d4a9380-eea8-11ea-82e8-4481a8cfabee.PNG">

**Comment by KermaniMojtaba** [comment] 2020-09-04 02:15
> I have access to multiple Windows machine and I had this issue in a couple of them. I pinned it down to the `node.js` requirement to install JupyterLab Extensions. I got this problem when I used the `conda install nodejs`. Instead when I installed the stable version of [Node.js](https://nodejs.org/en/) on top of Anaconda, it worked. No guarantee this will work for everyone, but it did for me to solve this issue.

Thanks for your help, I tried and didnt work for me

**Comment by edzkite** [comment] 2020-09-22 18:33
Closing as duplicate of https://github.com/kiteco/issue-tracker/issues/380

**Closed by edzkite** 2020-09-22 18:33 UTC
Labels: jupyterlab plugin, needs clarification
