### ISSUE TITLE
Kite pluging conflict/Disabled after updating JetBrain PyCharm from 2020.3 to 2021.1

### ISSUE THREAD

**Issue by Westendahl** [kiteco/issue-tracker#726] opened 2021-04-14 11:48 UTC
After updating JetBrain PyCharm from 2020.3 to 2021.1 I received a popup 'Conflicting Plugins' for 'Kite AI Code AutoComplete: Python .....'
The Kite plugin is now disabled and not working . 

https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/283731/kite_local/client.log.2021-04-14_01-41-01-PM.bak.gz

**Comment by hassanpydev** [comment] 2021-04-15 13:04
I have the same issue after updating from 2020.3 to 2021.1 I get 'Conflicting Plugins' and I have to disable Kite to get Pycharm run

**Comment by Popaulol** [comment] 2021-04-16 07:16
To Both of you, I have the same Problem but I know where it comes From, the new feature code with me added to Pycharm broke it.....

**Comment by Westendahl** [comment] 2021-04-16 07:29
The positive side ... the CPU-load is much less with Kite disabled and the fan-noise is now gone ;-)

**Comment by Westendahl** [comment] 2021-04-16 07:37
I just tried to disable the JetBrain plugin 'Code With Me' and reenable the Kite plugin.
That actually solved the Kite plugin problem and a way to go if you do not need the 'Code with me' feature.

**Comment by hassanpydev** [comment] 2021-04-16 21:51
> I just tried to disable the JetBrain plugin 'Code With Me' and reenable the Kite plugin.
> That actually solved the Kite plugin problem and a way to go if you do not need the 'Code with me' feature.

How did you disable JetBrain plugin 'Code With Me' ??

**Comment by Westendahl** [comment] 2021-04-19 07:09
File->Setting->Plugins .. 
1) Type 'Code with Me' in search field and disable (uncheck) the bundled plugin 'Code with me'.
2) Type Kite and reenable the Kite plugin
3) Restart PyCharm.

**Comment by edzkite** [comment] 2021-04-19 18:01
Closing as duplicate of https://github.com/kiteco/issue-tracker/issues/716

**Closed as completed by edzkite** 2021-04-19 18:01 UTC
Labels: bug, Needs Triage
