### ISSUE TITLE
Disable Kite for HTML and CSS file in VSCode

### ISSUE THREAD

**Issue by jasonmoy28** [kiteco/issue-tracker#456] opened 2020-10-31 07:57 UTC
Kite is a great auto-completion plugin for Python and Python only. When I am writing HTML and CSS file, Kite is always the first suggestion. But, Kite is suggestion is worse than Emmet suggestion. I still want to use Kite for Python file, but not with my HTML and CSS file. Is there a way to disable Kite for certain file type?

**Comment by metalogical** [comment] 2020-10-31 18:56
duplicate of https://github.com/kiteco/vscode-plugin/issues/339

We had released this setting last week, but had to roll back. It should be released again next week.

**Closed by metalogical** 2020-10-31 18:56 UTC
