### ISSUE TITLE
EDIT AUTO-COMPLETES!!

### ISSUE THREAD

**Issue by Aeronas** [kiteco/issue-tracker#476] opened 2020-11-10 19:07 UTC
Is there a way to edit what a multi-line auto-complete will enter?  If not, can this functionality be added??  There's not a lot of use in an auto-complete that does not follow PEP8 for Python and has to be edited after written anyway!

For example:

class auto-complete now:

```python3
class ClassName(object):
    """docstring for ClassName"""
    def __init__(self, arg):
        super(ClassName, self).__init__()
        self.arg = arg
```

class auto-complete as I would like it:
```python3
class ClassName(object):
    """docstring for ClassName"""

    def __init__(self, arg):
        self.arg = arg
```

Now I know it's easy enough to remove the super().__init__ as it highlights the entire line as I tab to it, but when I press del it only deletes the words, still have to delete the whitespace, then the line, then move up and add the extra line after docstring.

There has got to be a way to edit how this happens and allow users to customize this like PyCharm does in their settings...

**Comment by metalogical** [comment] 2020-11-10 19:24
thanks for the extra information, I'll close this as a duplicate of #475 – we'll track it there

**Closed by metalogical** 2020-11-10 19:24 UTC
