### ISSUE TITLE
Fedora 32 - JupyterLab_3.0 - Kite

### ISSUE THREAD

**Issue by kurotom** [kiteco/issue-tracker#522] opened 2020-12-26 02:19 UTC
**Describe the bug**
I followed all the instructions to be able to use "Kite" with "JupyterLab" in Fedora 32 and it could not be integrated, the icon does not appear in Jupyter, I attach information.

Please help, thanks.

**Screenshots**
![Captura de pantalla de 2020-12-25 23-11-55](https://user-images.githubusercontent.com/55354389/103144365-1c4bb980-4707-11eb-8fd8-0336ff50595c.png)

**Required Information**
[https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/615366/kite_local/client.log.2020-12-25_11-13-37-PM.bak.gz](url)

- OS
	Fedora release 32 (Thirty Two)
	Linux NAME 5.9.14-100.fc32.x86_64 # 1 SMP Fri Dec 11 14:30:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- rpm -qa | grep -i node
    nodejs-docs-12.18.4-1.fc32.noarch
    nodejs-full-i18n-12.18.4-1.fc32.x86_64
    nodejs-packaging-25-1.fc32.noarch
    nodejs-libs-12.18.4-1.fc32.x86_64
    nodejs-12.18.4-1.fc32.x86_64

- node --version
    v12.18.4

- jupyter labextension list
	JupyterLab v3.0.0
	Other labextensions (built into JupyterLab)
	   app dir: /home/NAME/.local/share/jupyter/lab
	        @kiteco/jupyterlab-kite v1.2.0 enabled OK

- jupyter serverextension list
	config dir: /usr/local/etc/jupyter
	    jupyter_kite  enabled 
	    - Validating...
	      jupyter_kite 1.2.0 OK

- pip list
    Package                       Version    
    ----------------------------- -----------
    anyio                         2.0.2      
    argcomplete                   1.10.0     
    args                          0.1.0      
    attrs                         20.2.0     
    Babel                         2.8.0      
    backcall                      0.1.0      
    Beaker                        1.10.0     
    beautifulsoup4                4.9.3      
    bleach                        3.1.4      
    blivet                        3.2.2      
    blivet-gui                    2.1.15     
    bokeh                         2.2.3      
    Bottleneck                    1.2.1      
    Brlapi                        0.7.0      
    cachetools                    4.2.0      
    certifi                       2020.11.8  
    cffi                          1.14.0     
    chardet                       3.0.4      
    chrome-gnome-shell            0.0.0      
    click                         7.1.2      
    clint                         0.5.1      
    cryptography                  2.8        
    cupshelpers                   1.0        
    cycler                        0.10.0     
    dasbus                        0.2        
    daterangestr                  0.0.3      
    dbus-python                   1.2.16     
    decorator                     4.4.0      
    defusedxml                    0.6.0      
    distro                        1.4.0      
    entrypoints                   0.3        
    et-xmlfile                    1.0.1      
    evdev                         1.3.0      
    fros                          1.1        
    future                        0.18.2     
    geocoder                      1.38.1     
    geojson                       2.5.0      
    google-api-core               1.23.0     
    google-auth                   1.23.0     
    google-auth-oauthlib          0.4.2      
    google-cloud-bigquery         2.6.1      
    google-cloud-bigquery-storage 2.1.0      
    google-cloud-core             1.4.4      
    google-crc32c                 1.0.0      
    google-resumable-media        1.1.0      
    googleapis-common-protos      1.52.0     
    gpg                           1.14.0     
    grpcio                        1.34.0     
    html5lib                      1.0.1      
    humanize                      0.5.1      
    idna                          2.8        
    iniconfig                     1.0.1      
    iotop                         0.6        
    ipdb                          0.12.3     
    ipykernel                     5.1.4      
    ipython                       7.12.0     
    ipython-genutils              0.1.0      
    jdcal                         1.4.1      
    jedi                          0.15.1     
    Jinja2                        2.11.2     
    json5                         0.9.5      
    jsonschema                    3.2.0      
    jupyter-client                6.1.7      
    jupyter-core                  4.6.1      
    jupyter-kite                  1.2.0      
    jupyter-server                1.1.3      
    jupyterlab                    3.0.0      
    jupyterlab-server             2.0.0      
    kiwisolver                    1.3.1      
    langtable                     0.0.53     
    libcomps                      0.1.15     
    libcst                        0.3.15     
    lxml                          4.4.1      
    Mako                          1.1.1.dev0 
    MarkupSafe                    1.1.1      
    matplotlib                    3.2.2      
    mistune                       0.8.3      
    mock                          3.0.5      
    mypy-extensions               0.4.3      
    nbclassic                     0.2.5      
    nbconvert                     5.6.0      
    nbformat                      5.0.4      
    netifaces                     0.10.6     
    nftables                      0.1        
    notebook                      6.0.2      
    ntplib                        0.3.3      
    numexpr                       2.7.1      
    numpy                         1.18.4     
    oauthlib                      3.1.0      
    olefile                       0.46       
    openpyxl                      3.0.5      
    openweather                   0.11       
    ordered-set                   3.1        
    OSMPythonTools                0.2.9      
    packaging                     20.4       
    pandas                        0.25.3     
    pandas-datareader             0.8.0      
    pandas-gbq                    0.14.1     
    pandocfilters                 1.4.1      
    parso                         0.5.2      
    Paste                         3.2.4      
    pdfkit                        0.6.1      
    pexpect                       4.7.0      
    pickleshare                   0.7.5      
    pid                           2.2.3      
    Pillow                        8.0.1      
    pip                           19.3.1     
    pluggy                        0.13.1     
    ply                           3.11       
    pprofile                      2.0.4      
    productmd                     1.30       
    prometheus-client             0.7.1      
    prompt-toolkit                2.0.10     
    proto-plus                    1.13.0     
    protobuf                      3.14.0     
    psutil                        5.7.0      
    ptyprocess                    0.6.0      
    pwquality                     1.4.4      
    py                            1.9.0      
    pyarrow                       2.0.0      
    pyasn1                        0.4.8      
    pyasn1-modules                0.2.8      
    pycairo                       1.18.2     
    pycparser                     2.19       
    pycrypto                      2.6.1      
    pycups                        2.0.1      
    pycurl                        7.43.0.5   
    pydata-google-auth            1.1.0      
    pyenchant                     2.0.0      
    Pygments                      2.4.2      
    PyGObject                     3.36.1     
    pyinotify                     0.9.6      
    pykickstart                   3.24       
    pyOpenSSL                     19.0.0     
    pyparsing                     2.4.7      
    pyparted                      3.11.4     
    PyPDF2                        1.26.0     
    pyproj                        3.0.0.post1
    pyrsistent                    0.16.0     
    PySocks                       1.7.1      
    pytest                        6.1.0      
    pytest-sugar                  0.9.4      
    python-augeas                 0.5.0      
    python-dateutil               2.8.0      
    python-meh                    0.48       
    python-xlib                   0.28       
    pytz                          2020.4     
    pyudev                        0.22.0     
    pyxdg                         0.26       
    PyYAML                        5.3.1      
    pyzmq                         18.1.0     
    ratelim                       0.1.6      
    reportlab                     3.5.56     
    requests                      2.22.0     
    requests-file                 1.4.3      
    requests-ftp                  0.3.1      
    requests-oauthlib             1.3.0      
    rpm                           4.15.1     
    rsa                           4.6        
    scipy                         1.4.1      
    scour                         0.37       
    seaborn                       0.11.0     
    selinux                       3.0        
    Send2Trash                    1.4.2      
    sepolicy                      3.0        
    setools                       4.3.0      
    setuptools                    41.6.0     
    simplegeneric                 0.8.1      
    simpleline                    1.6        
    six                           1.14.0     
    slip                          0.6.4      
    slip.dbus                     0.6.4      
    sniffio                       1.2.0      
    sos                           3.9        
    soupsieve                     1.9.2      
    systemd-python                234        
    tables                        3.5.2      
    Tempita                       0.5.1      
    termcolor                     1.1.0      
    terminado                     0.8.3      
    testpath                      0.3.1      
    toml                          0.10.1     
    tornado                       6.1        
    tqdm                          4.46.0     
    traitlets                     4.3.3      
    tweepy                        3.9.0      
    TwitterAPI                    2.6.2.1    
    twython                       3.8.2      
    typing-extensions             3.7.4.3    
    typing-inspect                0.6.0      
    tzlocal                       2.1        
    ujson                         4.0.1      
    urllib3                       1.25.7     
    wcwidth                       0.2.4      
    webencodings                  0.5.1      
    wkhtmltopdf                   0.2        
    xarray                        0.16.1     
    xlrd                          1.2.0      
    xlwt                          1.1.2      
    youtube-dl                    2020.12.2

**Comment by edzkite** [comment] 2021-01-04 20:25
Please see https://github.com/kiteco/issue-tracker/issues/532#issuecomment-754197763. Closing as duplicate of #532.

**Closed by edzkite** 2021-01-04 20:25 UTC
Labels: jupyterlab plugin

**Comment by edzkite** [comment] 2021-01-08 23:43
I've updated our extension to support JupyterLab 3.0, with [instructions to update](https://github.com/kiteco/issue-tracker/issues/532#issuecomment-757050104). Please let me know if this resolves things for you!
