### ISSUE TITLE
Stop this Auto-update not configured popup

### ISSUE THREAD

**Issue by Mizzlr** [kiteco/issue-tracker#173] opened 2020-02-11 20:00 UTC
Issue with uninstalling kite. 

Please follow the issue here https://github.com/sparkle-project/Sparkle/issues/1549

What is the correct way to uninstall kite and not break my mac's Sparkle.framework?

https://help.kite.com/category/51-uninstalling-kite Did not help.

**Comment by its-dhung** [comment] 2020-02-11 20:26
Try running the terminal command `launchctl remove com.kite.KiteHelper` and then uninstalling Kite. Let us know if this works for you.

**Comment by its-dhung** [comment] 2020-04-21 04:10
Closing this issue due to inactivity. @Mizzlr please let us know if you need further assistance.

**Comment by drizham** [comment] 2020-05-21 18:42
I have this same issue: tried launchctl remove com.kite.KiteHelper
Still having the issue HELP

**Comment by metalogical** [comment] 2020-05-21 21:11
Hi all,

Here are our next steps:
- Ensure we are updated to the latest version of Sparkle so that this pop-up doesn't show up (implied by https://github.com/sparkle-project/Sparkle/issues/1549#issuecomment-619251263).
- Do some digging to figure out how/why the Kite updater might possibly trigger.

We're still not entirely sure what the root cause is here, but will update the issue as we learn more.

**Comment by metalogical** [comment] 2020-05-21 21:20
@drizham @Mizzlr, did either of you install Kite via Homebrew by any chance? I discovered that a third party maintains a [Kite Homebrew Cask](https://formulae.brew.sh/cask/kite).

If so, Homebrew is not a supported installation method, and it's likely that when removing Kite it has not been properly removed from your system.

**Comment by metalogical** [comment] 2020-05-21 21:26
If not, could you paste the exact steps you took to remove Kite from your system?

It should match https://help.kite.com/article/68-how-to-uninstall-kite (ensure that no Kite processes are running before moving Kite.app to the trash)

**Comment by izuchukwu** [comment] 2020-05-21 22:58
Hi, I deleted the Kite plugin from Atom, then when I found my Atom install to no longer be working properly, searched then found and followed the guide at https://help.kite.com/article/68-how-to-uninstall-kite.

Now, I receive the popup mentioned in https://github.com/sparkle-project/Sparkle/issues/1549 several times a day.

What do I do here?

**Comment by adamsmith** [comment] 2020-05-21 23:18
@izuchukwu is your Trash empty? If not, is anything Kite-related in there?

Finally, could you try restarting your machine to see if this still happens?

**Comment by metalogical** [comment] 2020-05-22 16:10
As far as we can tell, this should only occur if some Kite process is still running. Rebooting should fix the issue. Please let us know if not.

**Comment by izuchukwu** [comment] 2020-05-22 16:50
I did find the Kite Engine process to still be running later that day. Terminating the process then logging out and in again seems to have solved it.

It may be helpful to terminate the process automatically as part of the uninstall process, or state that a restart/log out is required to complete the uninstall. While “off and on again” is something I should’ve tried sooner, I don’t usually restart my computer after adding or removing software unless told it’s required.

**Comment by drizham** [comment] 2020-05-25 11:59
emptied trash and restarted osx, that resolved it. Yes I did install via "brew cask install"

**Comment by metalogical** [comment] 2020-05-26 16:44
Thanks all.

I think the main point here is to clarify the uninstall process in the help page. Closing this issue, as it seems to be resolved.

**Closed by metalogical** 2020-05-26 16:44 UTC
