### ISSUE TITLE
in-editor side panel (copilot)

### ISSUE THREAD

**Issue by Khalilsqu** [kiteco/issue-tracker#258] opened 2019-09-19 01:18 UTC
I like Kite autocompletion in VScode. I have a suggestion to improve its usability. Is there any possibility to integrate Copilot into VScode as a help plugin? 

![image](https://user-images.githubusercontent.com/22060413/65203282-015db480-da83-11e9-89c3-08a547e9f268.png)

![image](https://user-images.githubusercontent.com/22060413/65203710-bee8a780-da83-11e9-8913-d117e10597c3.png)

**Comment by metalogical** [comment] 2020-06-09 01:46
duplicate of #126

**Closed by metalogical** 2020-06-09 01:46 UTC
