### ISSUE TITLE
Kite is automatically opening vscode (cli.js)

### ISSUE THREAD

**Issue by silverkhan** [kiteco/issue-tracker#239] opened 2020-05-27 04:36 UTC
This issue is the same as #171
After installing kite, vscode is automatically executed and the 'cli.js' file opens randomly.
Several people are experiencing this problem.

The link below is the application log created using kite.
https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/285412/kite_local/client.log.2020-05-27_01-30-14-PM.bak.gz

thanks.

**Comment by its-dhung** [comment] 2020-05-27 16:46
@metalogical this is likely the plugin manager opening VS Code when it's checking to see if the Kite plugin for VS Code is installed.

**Comment by metalogical** [comment] 2020-05-27 17:05
@silverkhan what version of VS Code are you running? what platform are you on?

**Comment by silverkhan** [comment] 2020-05-28 00:40
@metalogical 
Windows_NT x64 10.0.18362
Visual Studio Code, 1.45.1

**Comment by jansorg** [comment] 2020-05-28 14:06
I've been able to reproduce this:
1. Set "Visual Studio Code"  to run as administrator (Properties -> Compatibility -> Run program as administrator)
2. Run `"%UserProfile%\AppData\Local\Programs\Microsoft VS Code\bin\code" --list-extensions`
3. Due to `--list-extensions` it's supposed to print to the terminal, but a window is launched instead. It seems that the argument isn't passed to the process, which is launched with administrative permissions.

A temporary workaround for users is to disable `Run program as administrator` until this is resolved. 
Most likely Kite won't be able to install or update the extension with the setting enabled.

**Comment by metalogical** [comment] 2020-05-28 16:15
@silverkhan @ucxorc @3038922

Could you check if your "Visual Studio Code" is set to run as Administrator? We're currently operating on that assumption and investigating if there's any workaround we can implement on our end.

This issue is caused by an interaction between how Kite works and this VS Code bug: https://github.com/microsoft/vscode/issues/91613

**Comment by metalogical** [comment] 2020-05-29 18:03
the fix for "run as administrator" will be released next week

**Closed** 2020-06-03 16:15 UTC
Labels: plugin manager, prioritized
