### ISSUE TITLE
I have also face this problem. Please help me to get rid of this.

### ISSUE THREAD

**Issue by ramy-hue** [kiteco/issue-tracker#288] opened 2020-07-18 06:07 UTC
I have also face this problem. Please help me to get rid of this.
![Capture](https://user-images.githubusercontent.com/28803635/86494109-ccaeb580-bd95-11ea-9c49-63d6a44d2536.PNG)

_Originally posted by @reshma-ahmed58 in https://github.com/kiteco/issue-tracker/issues/118#issuecomment-653659302_

**Comment by its-dhung** [comment] 2020-07-20 15:58
Duplicate of #118

**Closed by its-dhung** 2020-07-20 15:58 UTC
Labels: duplicate
