### ISSUE TITLE
Kite Not Opening Mac Mini M1

### ISSUE THREAD

**Issue by ChrisF24** [kiteco/issue-tracker#513] opened 2020-12-18 01:33 UTC
When launching app it simply does not open. I tried reinstalling, still nothing. 

Hardware: Mac Mini M1 
Software: Big Sur 11.1

**Comment by metalogical** [comment] 2020-12-18 02:13
duplicate of #491

**Closed by metalogical** 2020-12-18 02:13 UTC

**Comment by sayedsadat98** [comment] 2021-04-01 19:28
Right now they are not yet supported on M1 chips and also they are not supported on Rosetta. You have to wait or subscribe to the newsletter so you will be notified. Check the link : https://help.kite.com/article/146-support-for-apple-m1-hardware
